name: CICD Pipeline

on:
  push:
    branches:
      - main


jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run check -- --outputFile=test-results.json --json

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/


  Deploy:
    runs-on: muntasir_k
    needs: Testing
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./test-results


      - name: Show Test Results
        run: cat ./artifacts/test-results.json

      - name: Install Dependencies
        run: npm install



      - name: Deploy to Server
        run: |
          ls -a
          pm2 status
          # pm2 restart all
          pm2 delete "Node Js Application" || true

          pm2 start "npm start" --name="Node Js Application"
          
          pm2 save

 



