name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run check

      - name: Build App
        run: npm run build

      - name: Upload Artifact (Build Files)
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/   # React/Vue হলে সাধারণত build ফোল্ডার, Node হলে dist


  Deploy:
    runs-on: kamal_t
    needs: Testing
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./build

      - name: Deploy to Server
        run: |
          ls -a ./build
          pm2 status
          pm2 delete "NodeJsStart" || true
          pm2 start "npm start" --name="NodeJsStart"
          pm2 save
