name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run check

      # ✅ এখানে build এর বদলে পুরো কোড বা dist artifact এ save করবো
      - name: Upload Project Files
        uses: actions/upload-artifact@v4
        with:
          name: project-files
          path: |
            ./
            !node_modules/
            !.git/
  

  Deploy:
    runs-on: kamal_t
    needs: Testing
    steps:
      - name: Download Project Files
        uses: actions/download-artifact@v4
        with:
          name: project-files
          path: ./app

      - name: Install Dependencies on Server
        run: |
          cd ./app
          npm install --production

      - name: Deploy to Server
        run: |
          cd ./app
          pm2 delete "NodeJsStart" || true
          pm2 start "npm start" --name="NodeJsStart"
          pm2 save
